### ISSUE TITLE
Every build = hard version?

### ISSUE THREAD

**Issue by JanJastrow** [TheFakeMateo/rpp-backup#1]
Hi there,
first, of course, thank you for this very cool project.
I have a problem: Whenever I build this repo (with ```make``` or ```make red```) when I start the game, it says it's the "hard dev version".
Anyway I can fix that?

**Comment by JustRegularLuna** [comment]
No offense but it literally explains this in the Readme...

**Comment by JanJastrow** [comment]
😖
Sorry

**Comment by JustRegularLuna** [comment]
It's ok
