### ISSUE TITLE
Description link is broken

### ISSUE THREAD

**Issue by ISSOtm** [TheFakeMateo/rpp-backup#13]
The repo's description contains https://github.com/TheFakeMateo/RedPlusPlus, which is now a broken link. Has it been moved?

**Comment by Rangi42** [comment]
RedPlusPlus was made private since people kept trying to play it way before it's ready. (Its development is on pause for other projects like [rgbs](https://github.com/TheFakeMateo/rgbs) ([map stitch](https://i.imgur.com/vSozsuS.png).)
