### ISSUE TITLE
Main repo is gone

### ISSUE THREAD

**Issue by halian** [TheFakeMateo/rpp-backup#14]
> This repo is for Red++ v3, which is the latest playable version. The main repo can be found at https://github.com/TheFakeMateo/RedPlusPlus if you want to keep up with progress on the upcoming v4 update.

Attempting to follow this link now results in a [404](https://http.cat/404).

**Comment by JustRegularLuna** [comment]
It is not gone, it is set to private because v4 has been on hold and is not in a playable state at the moment.
