### ISSUE TITLE
Hitmons not available

### ISSUE THREAD

**Issue by mkaziz** [TheFakeMateo/rpp-backup#16]
The fighting dojo only lets me pick up one hitmon and it looks like you removed them from Victory Road. This prevents pokedex completion. Is that intentional or is there something I'm missing? Feeling kinda bummed because I picked Red++ to finally experience pokedex completion.

**Comment by JustRegularLuna** [comment]
You can get all the hitmons you want. Just breed the one you picked at the daycare to get Tyrogues to evolve.

**Comment by mkaziz** [comment]
Oh good call, I didn't think about that. Thanks!

**Comment by JustRegularLuna** [comment]
no problem
