### ISSUE TITLE
Question About Sprites

### ISSUE THREAD

**Issue by GitHubQueenn** [TheFakeMateo/rpp-backup#18]
So, I love this ROM. BUT, is there a way to change these Gen 2 Pokémon and Trainer sprites to original Gen 1 ones? Seeing all the Gen 2 imagery makes me feel like I should just play Gen 2 instead

**Comment by JustRegularLuna** [comment]
You would have to make that change yourself by editing the .png images and compiling the rom again. I have no plans to include Gen 1 graphics as an official option, I'm sorry.
