### ISSUE TITLE
Edited the Red++ Files for my own Hack, Can't seem to build to .gbc....HELP!

### ISSUE THREAD

**Issue by Distortionex** [TheFakeMateo/rpp-backup#19]
Hi, thank you sooo much for this Red Hack Repository and the ability to make our own edits to the game! What I did was modify all pokemon's base stats, move changes, mart changes, etc, to make my own personal playthrough of the game (Not for public release). I've tried following instructions for Cygwin with this install tutorial and reading the Red Repository instructions and still cannot get it to build my file(s). Any way you could do it for me?

**Comment by JustRegularLuna** [comment]
It's possible you need an older version of the RGBDS compiler. I know I updated the repo months ago, but RGBDS has updated since then and might have broken things again. I'll check after work which version actually works.

**Comment by Distortionex** [comment]
^ Appreciate it! Got an error saying "Section BankF Grew too big (Max Size = 0x4000 bytes, reached 0x4001)."

**Comment by JustRegularLuna** [comment]
That last error means you tried to put too much stuff into that rom bank. Probably added too much when you were redoing things.

**Comment by Distortionex** [comment]
Ah, most of what I did was simple changes like Stats, Moves, Mart Items, Item Prices, etc. Didnt even "add" extra lines or anything. the only exception to that I guess was adding more Crit Moves to that section...could that be the issue?

**Comment by Distortionex** [comment]
Noticed the # of Lines for the Mart Changes I made were more than the original from your mod

**Comment by JustRegularLuna** [comment]
it might be the high crit moves you added. I think bank F has battle engine stuff and the battle engine takes up a lot of space already.

**Comment by JustRegularLuna** [comment]
Also if you want, it would probably be easier for me and others to help you if you joined my discord server. The link in the Readme should still work.
