### ISSUE TITLE
Ho-oh doesn't disappear after capture

### ISSUE THREAD

**Issue by twocows** [TheFakeMateo/rpp-backup#5]
I went to Navel Rock with 5 Pokemon in my party and caught Ho-oh first (before Lugia). I captured Ho-oh which added it to my party. It showed in my Pokedex, but the in-game sprite stayed there and could be interacted with, although it did not start another battle. It was still there after changing floors and coming back. I'm guessing this is a bug since it's the only one in the game that seems to do this. Version 3.0.2.

**Comment by JustRegularLuna** [comment]
Yeah this is a known bug. It doesn't really hurt anything, since he cannot be re-battled. v3 is not still receiving updates, and it won't be an issue in v4 due to it switching to Polished Crystal's game engine for that version.
