### ISSUE TITLE
Unable to build using MakeFile

### ISSUE THREAD

**Issue by TonioGela** [TheFakeMateo/rpp-backup#6]
As per issue title, I'm trying to build the repo and I get this message
`/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'extras/pokemontools/scan_includes.py'`
I saw that there's a extras folder under root that was meant to be populated with the python source of pokemontools (that I installed with pip)
Do I have to dump the content of extras from a previous commit to make the build work again?
I'm on macosx with rgbds install with the help of homebrew
Thanks and good luck for the developement of v4 (I successfully built it and tried it for a few minutes and it seems awesome)

**Comment by JustRegularLuna** [comment]
If the extras folder is empty, you cloned the repo incorrectly. The instructions tell you to use the --recursive flag when cloning the repo, so that it will checkout the submodule as well. Modern pokered doesn't work that way anymore, but Red++ did not pull in those changes from the vanilla repo.

**Comment by TonioGela** [comment]
Okay, my bad, as in 90% of cases the fault was not reading doc properly. I recloned and it works flawlessly. Sorry for bothering :)
